// <auto-generated />
using System;
using MeetingRoomBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingRoomBooking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MeetingRoomBooking.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Attendees")
                        .HasColumnType("int");

                    b.Property<string>("CancellationCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MeetingTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("RecurrenceGroupId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CancellationCode")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            Attendees = 20,
                            CancellationCode = "28e3bb9b-2dfa-43e6-8531-09e039d13d07",
                            Description = "Large conference room with Computer & HDMI",
                            Email = "desi@example.com",
                            EmployeeId = 2,
                            EndTime = new DateTime(2025, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCancelled = false,
                            MeetingTitle = "Weekly Marketing Sync",
                            RecurrenceGroupId = new Guid("d3f1c9e2-8a5b-4f2a-bf3a-9c3e2d1a7e99"),
                            RoomId = 1,
                            StartTime = new DateTime(2025, 8, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            BookingId = 2,
                            Attendees = 8,
                            CancellationCode = "b72e04b6-ad15-4ca3-b088-4ba06a190b6f",
                            Description = "Small conference with proyektor",
                            Email = "george@example.com",
                            EmployeeId = 3,
                            EndTime = new DateTime(2025, 8, 19, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCancelled = false,
                            MeetingTitle = "Weekly Marketing Sync",
                            RecurrenceGroupId = new Guid("a987fbc9-4bed-3078-cf07-9141ba07c9f3"),
                            RoomId = 3,
                            StartTime = new DateTime(2025, 8, 19, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("MeetingRoomBooking.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeId", "Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "desi@example.com",
                            EmployeeName = "Desi"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "raka@example.com",
                            EmployeeName = "Raka"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "george@example.com",
                            EmployeeName = "George"
                        });
                });

            modelBuilder.Entity("MeetingRoomBooking.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Amenities = "Tv,WhiteBoard",
                            Capacity = 20,
                            Description = "Large conference room with projector and video conferencing equipment.",
                            RoomName = "Conference Room A"
                        },
                        new
                        {
                            RoomId = 2,
                            Amenities = "Computer & HDMI",
                            Capacity = 10,
                            Description = "Small-sized meeting room for team discussions.",
                            RoomName = "Conference Room B"
                        },
                        new
                        {
                            RoomId = 3,
                            Amenities = "Proyektor",
                            Capacity = 15,
                            Description = "Medium-sized meeting room for team discussions.",
                            RoomName = "Conference Room C"
                        });
                });

            modelBuilder.Entity("MeetingRoomBooking.Models.Booking", b =>
                {
                    b.HasOne("MeetingRoomBooking.Models.Employee", "Employee")
                        .WithMany("Bookings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingRoomBooking.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MeetingRoomBooking.Models.Employee", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MeetingRoomBooking.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
